buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // ✅ UPDATED AGP
        classpath 'com.android.tools.build:gradle:8.9.1'

        // Google services same rakho
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}